controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
faq:
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    path: /faq
    defaults:
        template: faq.twig