controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

technician_profile:
    path: /technician/profile/{id}
    controller: App\Controller\UserController::profile
    methods: GET
