# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    uploads_base_url: '%env(UPLOADS_BASE_URL)%'

services:
    _defaults:
        bind:
            $mailerFromAddress: 'rwayed-admin@test.com'
            $secretKey: '%env(RECAPTCHA3_SECRET)%'
            $uploadsBaseUrl: '%env(UPLOADS_BASE_URL)%'
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    # default configuration for services in *this* file
    App\Services\PneuManager: ~
    App\Services\PasswordHasherService:
        arguments:
            $passwordHasher: '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'

    App\EventSubscriber\PneuPreRemoveSubscriber:
        tags:
            - { name: 'doctrine.event_subscriber' }
    App\EventSubscriber\PneuFormSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }

    App\EventSubscriber\AvisDeletedListener:
        tags:
            - { name: 'kernel.event_listener', event: 'avis.deleted', method: 'onAvisDeleted' }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Aws\S3\S3Client:
        arguments:
            - version: '%env(MINIO_VERSION)%'
              region: '%env(MINIO_REGION)%'
              endpoint: '%env(MINIO_ENDPOINT)%'
              use_path_style_endpoint: '%env(bool:MINIO_USE_PATH_STYLE_ENDPOINT)%'
              credentials:
                  key: '%env(MINIO_USER)%'
                  secret: '%env(MINIO_PASSWORD)%'